version: "3.9"

services:
  db:
    image: postgres:16
    container_name: the-project-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: the_project_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  # staging:
  #   build: .
  #   container_name: the-project
  #   env_file:
  #     - .env
  #   environment:
  #     APP_ENV: ${APP_ENV:-dev}
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   volumes:
  #     - .:/app
  #   restart: unless-stopped

volumes:
  postgres_data: